// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkVQ7oYLK1ao13TqoKbE7iMHV1qprcnko',
    appId: '1:771566350646:web:269387f0d2793326fac397',
    messagingSenderId: '771566350646',
    projectId: 'student-pulse-ecbc9',
    authDomain: 'student-pulse-ecbc9.firebaseapp.com',
    storageBucket: 'student-pulse-ecbc9.appspot.com',
    measurementId: 'G-41ZW8G1B3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw9waqwL9SvXA42d-YHrva5DDV1EMaIcg',
    appId: '1:771566350646:android:3cccc8f9f3cbbb3bfac397',
    messagingSenderId: '771566350646',
    projectId: 'student-pulse-ecbc9',
    storageBucket: 'student-pulse-ecbc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQlWReNp-CiG8D6E5u52jNszvAMJhr7Sk',
    appId: '1:771566350646:ios:ad0cc97b353cd111fac397',
    messagingSenderId: '771566350646',
    projectId: 'student-pulse-ecbc9',
    storageBucket: 'student-pulse-ecbc9.appspot.com',
    iosClientId: '771566350646-fonpigp18j8u5aduc3t5agijvjuc9se4.apps.googleusercontent.com',
    iosBundleId: 'com.studentpulse.studentPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQlWReNp-CiG8D6E5u52jNszvAMJhr7Sk',
    appId: '1:771566350646:ios:bee5772a031ba3ddfac397',
    messagingSenderId: '771566350646',
    projectId: 'student-pulse-ecbc9',
    storageBucket: 'student-pulse-ecbc9.appspot.com',
    iosClientId: '771566350646-8edq69q2rrmd72qll98mekfnnmtq932s.apps.googleusercontent.com',
    iosBundleId: 'com.studentpulse.studentPulse.RunnerTests',
  );
}
